mediaplayer = "YoutubeMusic"	# The music player. supports VLC and Youtube music properly, does not work on windows right now.
minimalBackground = true		# Whether to have a very small chatbox background or not


[[lines]]
interval = 6e3					# the time between changing the message,
								# the number before the e3 dictates seconds, do not change e3 unless you want to be precise with milliseconds.
order = "normal"				# can be "normal", "reverse", or "random"

messages = [					# The messages
	"silly car",
	"im EVIL",
	"i hate everyone",
	"i am BITING YOU"
]

[[lines]]
message = "{time} | CPU: {cpuTemp} | RAM: {ramPercentage}"

[[lines]]
message = "{music}"

[[lines]]
interval = 5e3
order = "normal"
messages = [
	"{musicProgressBar}",
	"CPU: {cpuName}"
]

[[lines]]
interval = 5e3
order = "normal"
messages = [
	"{musicPosition}",
	"GPU: {gpuName}"
]
